<?php
/**
 * Страница "Форма добавления / редактирования пункта меню".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Form for adding/editing a menu item</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/form.png' ?>" />
    </div>
    <p>The form appears after clicking the <b>"Add"</b> button on the menu item list toolbar or selecting the <b>"Edit"</b> item from the context menu of the selected entry.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_spinner"></span> <b>Index.</b> The index number of the menu item. Used to sort items within its nesting;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Name.</b> Menu item name;</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Menu section.</b> The menu section is specified if it is necessary to add a menu sub-item to the item (section);</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Plugin.</b> ЕIf a plugin is selected, then sub-items will be added to the menu item you created in accordance with the selected plugin;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Icon.</b> CSS class of menu item icon;</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Enabled.</b> If a menu item is not available, it will not be highlighted;</li>
        <li><span class="g-help-fld g-help-fld_checkbox"></span> <b>Visible.</b> Show or hide menu item.</li>
    </ul>

    <h3>Menu item type</h3>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Type.</b> Type (xtype объекта <a target="_blank" href="https://docs.sencha.com/extjs/5.1.1/api/Ext.menu.Item.html">Ext.menu.Item</a>) menu item. If not specified, "menuitem" is used;</li>
        <li><span class="g-help-fld g-help-fld_textarea"></span> <b>Attributes.</b>Attributes are properties of an object <a target="_blank" href="https://docs.sencha.com/extjs/5.1.1/api/Ext.menu.Item.html">Ext.menu.Item</a> menu items are indicated through the separator ",". For example, "width=100;height=20".</li>
    </ul>

    <h3>Menu item event handler</h3>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Name.</b> Event name (JavaScript function).</li>
        <li><span class="g-help-fld g-help-fld_textarea"></span> <b>Arguments.</b>Arguments passed to the event are specified using the separator ",". For example, "url=https://domain.com;action=open".</li>
    </ul>
</article>