<?php
/**
 * Страница "Список пунктов меню".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Список пунктов меню</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/grid.png' ?>" />
    </div>
    <p>В списке отображаются все пункты главного меню Панели управления.</p>
    <h2>Столбцы списка</h2>
    <ul class="g-help-list">
        <li><b>Порядок.</b> Порядковый номер пункта меню;</li>
        <li><b>Название.</b> Название пункта меню;</li>
        <li><b>Название (текущий язык).</b> Название пункта меню для текущего языка;</li>
        <li><b>Значок / Изображение.</b> Значок или изображение пункта меню;</li>
        <li><b>Подпунктов.</b> Количество подпунктов в пункте меню;</li>
        <li><b>Роли пользователей.</b> Роли пользователей которым доступны пункты меню;</li>
        <li><b>Доступность.</b> Если пункт меню не доступен, он не будет выделяться.</li>
        <li><b>Видимость.</b> Показать или скрыть пункт меню.</li>
    </ul>

    <h2>Панель инструментов</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-add.svg' ?>" /> <b>Добавить.</b> Вызывает форму для добавления пункта меню;</li>
        <li><img class="g-help-icon" src="<?= $assetsUrl, '/images/icon-delete.svg' ?>" /> <b>Удалить.</b> Удаляет выделенные пункты меню;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/cleanup.svg' ?>" /> <b>Очистить.</b> Удаляет все пункты меню;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-edit.svg' ?>" /> <b>Правка.</b> Вызвает форму для редактирования пункта меню;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-select.svg' ?>" /> <b>Выделить.</b> Выделяет или убирает выделение пунктов меню;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Обновить.</b> Обновляет список пунктов меню;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Профилирование записи.</b> Разворачивает или сворачивает Панель навигации для отображения информации о пункте меню;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-toggle-columns-off.svg' ?>" /> <b>Показать / Скрыть.</b> Показывает  скрытые столбцы;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Справка.</b> Вызывает окно справочной информации для текущего списка;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Поиск.</b> Вызывает форму поиска записей в списке;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/filter.svg' ?>" /> <b>Фильтр.</b> Вызывает форму фильтрации записей в списке.</li>
    </ul>
</article>